name: Deploy to EC2

on:
  push:
    branches: [ main ]  # 혹은 master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      # EC2 서버 접속을 위한 키 파일 설정
      - name: Create SSH Directory
        run: mkdir -p ~/.ssh/

      - name: Store Private Key
        run: echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/nugu-backend-key.pem

      - name: Set Key Permissions
        run: chmod 600 ~/.ssh/nugu-backend-key.pem

      # 기존 프로세스 종료 및 백업
      - name: Stop and Backup Existing Application
        run: |
          ssh -i ~/.ssh/nugu-backend-key.pem -o StrictHostKeyChecking=no ubuntu@ec2-54-180-124-235.ap-northeast-2.compute.amazonaws.com '
            if pgrep java; then
              pid=$(pgrep java)
              kill -15 $pid
              sleep 10
            fi
            if [ -f ~/app/Nugu-0.0.1-SNAPSHOT.jar ]; then
              mv ~/app/Nugu-0.0.1-SNAPSHOT.jar ~/app/Nugu-0.0.1-SNAPSHOT.jar.backup
            fi
          '

      # 새 JAR 파일 전송
      - name: Copy JAR file to EC2
        run: |
          scp -i ~/.ssh/nugu-backend-key.pem -o StrictHostKeyChecking=no ./build/libs/Nugu-0.0.1-SNAPSHOT.jar ubuntu@ec2-54-180-124-235.ap-northeast-2.compute.amazonaws.com:~/app/

      # 애플리케이션 시작
      - name: Start Application
        run: |
          ssh -i ~/.ssh/nugu-backend-key.pem -o StrictHostKeyChecking=no ubuntu@ec2-54-180-124-235.ap-northeast-2.compute.amazonaws.com '
            cd ~/app
            nohup java -jar Nugu-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &
          '